# Spring configuration file
---
spring:
  profiles: default
  ### General Information ###
  application:
      name: cf-service-broker-mongodb
  ### Security ###
  ssl:
    acceptselfsigned: true
  cloud:
    enabled: false
    features:
      enabled: false
  ### Cloud Config ###
  #  cloud:
  #    config:
  #      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8081}

  ### Deployment ###
  #### Docker ####
  rabbitmq:
    host:
    port:
    username:
    password:
    # virtual-host:
    template:
      reply-timeout: 120000

  data: &data
    mongodb:
      host: mongo
      port: 27017
      username: root
      password: secret
      database: admin

### General Information ###
info:
  app:
    name: MongoDB Service Broker
    description: MongoDB Service Broker for Cloud Foundry Service Deployments
    version: 0.1-RC

server:
  port: ${SERVER_PORT:8080}


### Logging ###
logging:
  #file: ${LOG_FILE:cf-service-broker-mongodb.log}
  level:
    root: INFO

### Service ###
backend:
  ports:
    default:
  connection:
    timeouts:

mongodb:
  security:
    key:
      length: 741

### Persistence ###
#### Redis ####
redis:
  host:
  port:
  password:
  timeout: 5
  retries: 20
  param:

### Service Key Generation ###
#### HAProxy ####
haproxy:
  uri:
  auth:
    token:

### Deployment ###
deployment:
  repo:
    main:
      uri:
    monit:
      uri:
    service:
      uri:


### Deployment ###
#### Docker ####
docker:
  imageName:
  offset:
  host:
  port:
  portRange:
    start:
    end:
  ssl:
    enabled: false
  syslogAddress:

#### OpenStack ####
#openstack:
#  endpoint:
#  username:
#  password:
#  tenantId:
#  networkId:
#  subnetId:
#  imageId:
#  keypair:
#  log_host:
#  log_port:
#  cinder:
#    az:

login:
  username: pants
  password: qqqxqwd
  role: ADMIN

existing:
  endpoint:
    hosts:
    - mongo.<host>
    port: 27017
    username: root
    password: secret

catalog:
  services:
  - id: sample-service
    name: sample-service
    description: Some service
    bindable: true
    plans:
    - id: sample-free
      name: free
      description: Free
      metadata: {}
      free: true
      platform: EXISTING_SERVICE
    tags: []
    metadata: {}
    requires: []